		<div id="footer" class="text-center">    
			<h5>Copyright Hugo Roche 2015</h5>
		</div>
		
		
		
		<script src="<?php echo $this->baseUrl().'/js/jquery.js'?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl().'/js/jquery-ui.js'?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl().'/js/menu.js'?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl().'/boostrap3/js/bootstrap.js'?>" type="text/javascript"></script>

</body>