<div class="container-fluid">
	<div class="row" id="carousel">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
		  </ol>

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
		    <div class="item active">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel1.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel2.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel3.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel4.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel5.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		  </div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-xs-8">
			<div class="row">
				<img id="boutique-noel" src="<?php echo $this->baseUrl().'/imgs/boutique-noël.jpg' ?>" alt="img_boutique-noël"/>
			</div>
			
						<div class="row">
				<h4>En lien avec des articles que vous avez regardés <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_1">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img19.jpg' ?>" alt="Modèle 19">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img20.jpg' ?>" alt="Modèle 20">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img21.jpg' ?>" alt="Modèle 21">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img22.jpg' ?>" alt="Modèle 22">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_1" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_1" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<h4>Baisse de prix : console PS4 à partir de 299,99€ <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_2">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel2/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_2" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_2" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<h4>Idées cadeaux High-Tech pour les fans de gadgets <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_3">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img19.jpg' ?>" alt="Modèle 19">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img20.jpg' ?>" alt="Modèle 20">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img21.jpg' ?>" alt="Modèle 21">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel3/img22.jpg' ?>" alt="Modèle 22">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_3" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_3" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<h4>Consoles <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_4">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel4/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_4" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_4" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<h4>Notre sélection d'enceintes portables <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_5">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img19.jpg' ?>" alt="Modèle 19">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img20.jpg' ?>" alt="Modèle 20">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img21.jpg' ?>" alt="Modèle 21">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img22.jpg' ?>" alt="Modèle 22">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img23.jpg' ?>" alt="Modèle 23">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img24.jpg' ?>" alt="Modèle 24">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img25.jpg' ?>" alt="Modèle 25">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel5/img26.jpg' ?>" alt="Modèle 26">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_5" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_5" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<h4>Idées cadeaux High-Tech pour les débutants <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_6">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img19.jpg' ?>" alt="Modèle 19">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img20.jpg' ?>" alt="Modèle 20">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel6/img21.jpg' ?>" alt="Modèle 21">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_6" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_6" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<h4>Jeux vidéo les plus offerts <a href="#" class="lien_voir_plus">Voir plus</a></h4>
				<div class="carousel_produits" id="carousel_7">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img19.jpg' ?>" alt="Modèle 19">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img20.jpg' ?>" alt="Modèle 20">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img21.jpg' ?>" alt="Modèle 21">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img22.jpg' ?>" alt="Modèle 22">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img23.jpg' ?>" alt="Modèle 23">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img24.jpg' ?>" alt="Modèle 24">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img25.jpg' ?>" alt="Modèle 25">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img26.jpg' ?>" alt="Modèle 26">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img27.jpg' ?>" alt="Modèle 27">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img28.jpg' ?>" alt="Modèle 28">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img29.jpg' ?>" alt="Modèle 29">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img30.jpg' ?>" alt="Modèle 30">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img31.jpg' ?>" alt="Modèle 31">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img32.jpg' ?>" alt="Modèle 32">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel7/img33.jpg' ?>" alt="Modèle 33">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" id="prev_7" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" id="next_7" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<div class="col-xs-6">
					<p>Soyez livrés à temps pour noël</p>
				</div>
				<div class="col-xs-6">
					<p>Vente flash pour noël</p>
				</div>
			</div>
		</div>
		<div class="col-xs-4" id="bloc-publicitaire">
			<div class="row publicite">
				<p>Amazon utilise des cookies. <a href="#">En savoir plus.</a></p>
				<hr>
			</div>
			<div class="row publicite">
				<p>LA Y EN A UNE AUTRE</p>
			</div>
		</div>
	</div>
</div>