<div class="container-fluid">
	<div class="row" id="carousel">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
		  </ol>

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
		    <div class="item active">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel1.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel2.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel3.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel4.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		    <div class="item">
		      <img src="<?php echo $this->baseUrl().'/imgs/carousel5.jpg' ?>" alt="..." data-holder-rendered="true">
		    </div>
		  </div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-xs-8">
			<div class="row">
				<img id="boutique-noel" src="<?php echo $this->baseUrl().'/imgs/boutique-noël.jpg' ?>" alt="img_boutique-noël"/>
			</div>
			
						<div class="row">
				<div class="carousel_produits">
					<ul>
						<li class="carousel-item first">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img1.jpg' ?>" alt="Modèle 1">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img2.jpg' ?>" alt="Modèle 2">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img3.jpg' ?>" alt="Modèle 3">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img4.jpg' ?>" alt="Modèle 4">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img5.jpg' ?>" alt="Modèle 5">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img6.jpg' ?>" alt="Modèle 6">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img7.jpg' ?>" alt="Modèle 7">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img8.jpg' ?>" alt="Modèle 8">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img9.jpg' ?>" alt="Modèle 9">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img10.jpg' ?>" alt="Modèle 10">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img11.jpg' ?>" alt="Modèle 11">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img12.jpg' ?>" alt="Modèle 12">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img13.jpg' ?>" alt="Modèle 13">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img14.jpg' ?>" alt="Modèle 14">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img15.jpg' ?>" alt="Modèle 15">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img16.jpg' ?>" alt="Modèle 16">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img17.jpg' ?>" alt="Modèle 17">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img18.jpg' ?>" alt="Modèle 18">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img19.jpg' ?>" alt="Modèle 19">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img20.jpg' ?>" alt="Modèle 20">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img21.jpg' ?>" alt="Modèle 21">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
						<li class="carousel-item last">
							<img src="<?php echo $this->baseUrl().'/imgs/img_carousel/carousel1/img22.jpg' ?>" alt="Modèle 22">
							<input class="carousel-btn" type="submit" value="Aperçu rapide">
						</li>
					</ul>
					
				</div>
				<a class="carousel_controls carousel_produits-prev" href="#"><span class="glyphicon glyphicon-chevron-left glyphicon-carousel"></span></a>
				<a class="carousel_controls carousel_produits-next" href="#"><span class="glyphicon glyphicon-chevron-right glyphicon-carousel"></span></a>
			</div>
			
			<div class="row">
				<div class="col-xs-6">
					<p>Soyez livrés à temps pour noël</p>
				</div>
				<div class="col-xs-6">
					<p>Vente flash pour noël</p>
				</div>
			</div>
		</div>
		<div class="col-xs-4" id="bloc-publicitaire">
			<div class="row publicite">
				<p>Amazon utilise des cookies. <a href="#">En savoir plus.</a></p>
				<hr>
			</div>
			<div class="row publicite">
				<p>LA Y EN A UNE AUTRE</p>
			</div>
		</div>
	</div>
</div>